name: Deploy to Google App Engine

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: awesome-testing-1681473100176
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: ./mvnw -DskipTests package

    - name: Deploy to Google App Engine
      run: ./mvnw -DskipTests appengine:deploy

    # - name: Verify deployment
    #   run: curl -I https://$GAE_PROJECT_ID.appspot.com

